### ISSUE TITLE
关于cargo test

### ISSUE THREAD

**Issue by wulalawu0106** [hkbudb/vchain-demo#2]
您好，我在尝试运行vchain-node,vchain-server的时候，会有如下提示

thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /home/wulalawu/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/tokio-1.13.0/src/runtime/context.rs:18:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Panic in Arbiter thread.

想请教您该如何解决这些问题.

**Comment by zhangwei9813** [comment]
请问你解决了吗

**Comment by zhang-zw123** [comment]
> 您好，我在尝试运行vchain-node,vchain-server的时候，会有如下提示
> 
> thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /home/wulalawu/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/tokio-1.13.0/src/runtime/context.rs:18:26 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace Panic in Arbiter thread.
> 
> 想请教您该如何解决这些问题.

请问你解决了吗？

**Comment by zhangwei9813** [comment]
> 您好，我在尝试运行vchain-node,vchain-server的时候，会有如下提示
> 
> thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /home/wulalawu/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/tokio-1.13.0/src/runtime/context.rs:18:26 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace Panic in Arbiter thread.
> 
> 想请教您该如何解决这些问题.

thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime'
这个问题应如何解决啊

**Comment by wulalawu0106** [comment]
> > 您好，我在尝试运行vchain-node,vchain-server的时候，会有如下提示
> > thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /home/wulalawu/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/tokio-1.13.0/src/runtime/context.rs:18:26 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace Panic in Arbiter thread.
> > 想请教您该如何解决这些问题.
> 
> 请问你解决了吗？

这个demo我没有完全运行成功，如果是 thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', 这个问题，运行程序时 ./vchain-node 的 “./” 别忘了

**Comment by zhangwei9813** [comment]
> > > 您好，我在尝试运行vchain-node,vchain-server的时候，会有如下提示
> > > thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /home/wulalawu/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/tokio-1.13.0/src/runtime/context.rs:18:26 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace Panic in Arbiter thread.
> > > 想请教您该如何解决这些问题.
> > 
> > 
> > 请问你解决了吗？
> 
> 这个demo我没有完全运行成功，如果是 thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', 这个问题，运行程序时 ./vchain-node 的 “./” 别忘了
在执行这步时，url    http://127.0.0.1:5000/api/explorer/v1/transactions不能访问，你知道是什么原因吗
let res = client.post(&tx_url).json(&json!({ "tx_body": tx_message })).send().await?;

**Comment by zhang-zw123** [comment]
let res = client.post(&tx_url).json(&json!({ "tx_body": tx_message })).send().await?;为什么这一步请求没反应？

**Comment by zhangwei9813** [comment]
复现这东西，对我这菜鸡真难啊，哭了。

**Comment by 1509769813** [comment]
> > > 您好，我在尝试运行vchain-node,vchain-server的时候，会有如下提示
> > > thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /home/wulalawu/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/tokio-1.13.0/src/runtime/context.rs:18:26 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace Panic in Arbiter thread.
> > > 想请教您该如何解决这些问题.
> > 
> > 
> > 请问你解决了吗？
> 
> 这个demo我没有完全运行成功，如果是 thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', 这个问题，运行程序时 ./vchain-node 的 “./” 别忘了
为什么我加./就是错误的
D:\code\rust\vchain-demo-master>cargo run --bin ./vchain-node -- --bit-len 16,16 --skip-list-max-level 5 --db /path/to/database
error: no bin target named `./vchain-node`

        Did you mean `vchain-node`?

只有D:\code\rust\vchain-demo-master>cargo run --bin vchain-node -- --bit-len 16,16 --skip-list-max-level 5 --db path/to/database这样才能运行？

**Comment by r4sk01** [comment]
Hello, have the same issue:

`$ ./target/release/vchain-server -b 127.0.0.1:8000
thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /home/r4sk01/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/context.rs:31:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Panic in Arbiter thread.`

How to solve it?
